version: '3.9'
services:
  db:
    image: postgres:15
    restart: always
    env_file: .env
    ports:
      - '5432:5432'
    volumes: 
      - ./db:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
volumes:
  db:
    driver: local

networks:
  network: {}
